### Q3.  Load the data from wine dataset. Check whether all attributes are standardized or not (mean is 0 and standard deviation is 1). If not, standardize the attributes. Do the same with Iris dataset.

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv('winequalityN.csv')

In [4]:
df

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
4     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6492    red            6.2             0.600         0.08             2.0   
6493    red            5.9             0.550         0.10             2.2   
6494    red            6.3             0.510         0.13             2.3   
6495    red            5.9             0.645         0.12             2.0   
6496    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
4         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6492      0.090                 32.0                  44.0  0.99490  3.45   
6493      0.062                 39.0                  51.0  0.99512  3.52   
6494      0.076                 29.0                  40.0  0.99574  3.42   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
4          0.40      9.9        6  
...         ...      ...      ...  
6492       0.58     10.5        5  
6493        NaN     11.2        6  
6494       0.75     11.0        6  
6495       0.71     10.2        5  
6496       0.66     11.0        6  

[6497 rows x 13 columns]

In [5]:
df.isna().sum().sum()

38

In [6]:
df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

In [7]:
df

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
4     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6458    red            6.8             0.620         0.08             1.9   
6459    red            6.2             0.600         0.08             2.0   
6460    red            6.3             0.510         0.13             2.3   
6461    red            5.9             0.645         0.12             2.0   
6462    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
4         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6458      0.068                 28.0                  38.0  0.99651  3.42   
6459      0.090                 32.0                  44.0  0.99490  3.45   
6460      0.076                 29.0                  40.0  0.99574  3.42   
6461      0.075                 32.0                  44.0  0.99547  3.57   
6462      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
4          0.40      9.9        6  
...         ...      ...      ...  
6458       0.82      9.5        6  
6459       0.58     10.5        5  
6460       0.75     11.0        6  
6461       0.71     10.2        5  
6462       0.66     11.0        6  

[6463 rows x 13 columns]

In [8]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6463.000000       6463.000000  6463.000000     6463.000000   
mean        7.217755          0.339589     0.318758        5.443958   
std         1.297913          0.164639     0.145252        4.756852   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6463.000000          6463.000000           6463.000000  6463.000000   
mean      0.056056            30.516865            115.694492     0.994698   
std       0.035076            17.758815             56.526736     0.003001   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992330   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.997000   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  6463.000000  6463.000000  6463.000000  6463.000000  
mean      3.218332     0.531150    10.492825     5.818505  
std       0.160650     0.148913     1.193128     0.873286  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.110000     0.430000     9.500000     5.000000  
50%       3.210000     0.510000    10.300000     6.000000  
75%       3.320000     0.600000    11.300000     6.000000  
max       4.010000     2.000000    14.900000     9.000000

### Standardization needed

In [9]:
df

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
4     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6458    red            6.8             0.620         0.08             1.9   
6459    red            6.2             0.600         0.08             2.0   
6460    red            6.3             0.510         0.13             2.3   
6461    red            5.9             0.645         0.12             2.0   
6462    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
4         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6458      0.068                 28.0                  38.0  0.99651  3.42   
6459      0.090                 32.0                  44.0  0.99490  3.45   
6460      0.076                 29.0                  40.0  0.99574  3.42   
6461      0.075                 32.0                  44.0  0.99547  3.57   
6462      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
4          0.40      9.9        6  
...         ...      ...      ...  
6458       0.82      9.5        6  
6459       0.58     10.5        5  
6460       0.75     11.0        6  
6461       0.71     10.2        5  
6462       0.66     11.0        6  

[6463 rows x 13 columns]

In [10]:
X = df.iloc[:, 1:-1]

In [11]:
X

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36            20.7      0.045   
1               6.3             0.300         0.34             1.6      0.049   
2               8.1             0.280         0.40             6.9      0.050   
3               7.2             0.230         0.32             8.5      0.058   
4               7.2             0.230         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
6458            6.8             0.620         0.08             1.9      0.068   
6459            6.2             0.600         0.08             2.0      0.090   
6460            6.3             0.510         0.13             2.3      0.076   
6461            5.9             0.645         0.12             2.0      0.075   
6462            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
6458                 28.0                  38.0  0.99651  3.42       0.82   
6459                 32.0                  44.0  0.99490  3.45       0.58   
6460                 29.0                  40.0  0.99574  3.42       0.75   
6461                 32.0                  44.0  0.99547  3.57       0.71   
6462                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         8.8  
1         9.5  
2        10.1  
3         9.9  
4         9.9  
...       ...  
6458      9.5  
6459     10.5  
6460     11.0  
6461     10.2  
6462     11.0  

[6463 rows x 11 columns]

In [12]:
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# X = np.array(ct.fit_transform(X))

In [13]:
scaler = StandardScaler()

In [14]:
X = scaler.fit_transform(X)

In [15]:
X

array([[-0.16778609, -0.42270958,  0.2839587 , ..., -1.35916011,
        -0.5449872 , -1.41892232],
       [-0.70715516, -0.2404789 ,  0.14625658, ...,  0.50839916,
        -0.27635393, -0.83218392],
       [ 0.67979387, -0.36196602,  0.55936296, ...,  0.25939126,
        -0.61214551, -0.32926528],
       ...,
       [-0.70715516,  1.03513588, -1.29961576, ...,  1.25542287,
         1.46976231,  0.42511267],
       [-1.01536606,  1.85517396, -1.36846682, ...,  2.18920251,
         1.20112905, -0.24544551],
       [-0.93831333, -0.17973534,  1.0413204 , ...,  1.06866695,
         0.86533746,  0.42511267]])

In [16]:
np.mean(X, axis=0)

array([-1.23132889e-16, -2.11084953e-16, -8.79520638e-17,  1.93494540e-16,
       -7.03616511e-17, -7.03616511e-17,  1.05542477e-16,  5.21995499e-14,
        9.85063115e-16,  1.40723302e-16, -5.45302796e-16])

In [17]:
np.round(np.mean(X, axis=0), decimals=2)

array([-0., -0., -0.,  0., -0., -0.,  0.,  0.,  0.,  0., -0.])

In [18]:
np.std(X, axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Iris Dataset

In [19]:
df = pd.read_csv('./Iris.csv', index_col='Id')

In [20]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id                                                                           
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [21]:
df.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [22]:
df.describe()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [23]:
X = df.iloc[:, 0:-1]

In [24]:
X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Id                                                           
1              5.1           3.5            1.4           0.2
2              4.9           3.0            1.4           0.2
3              4.7           3.2            1.3           0.2
4              4.6           3.1            1.5           0.2
5              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
146            6.7           3.0            5.2           2.3
147            6.3           2.5            5.0           1.9
148            6.5           3.0            5.2           2.0
149            6.2           3.4            5.4           2.3
150            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [25]:
X = scaler.fit_transform(X)

In [ ]:
X

In [27]:
np.mean(X, axis=0)

array([-4.73695157e-16, -6.63173220e-16,  3.31586610e-16, -2.84217094e-16])

In [28]:
np.round(np.mean(X, axis=0), 2)

array([-0., -0.,  0., -0.])

In [29]:
np.std(X, axis=0)

array([1., 1., 1., 1.])