In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('weather.csv')

In [3]:
df

Outlook Temperature Humidity   Windy Play
0      Sunny         Hot     High    Weak   No
1      Sunny         Hot     High  Strong   No
2   Overcast         Hot     High    Weak  Yes
3       Rain        Mild     High    Weak  Yes
4       Rain        Cool   Normal    Weak  Yes
5       Rain        Cool   Normal  Strong   No
6   Overcast        Cool   Normal  Strong  Yes
7      Sunny        Mild     High    Weak   No
8      Sunny        Cool   Normal    Weak  Yes
9       Rain        Mild   Normal    Weak  Yes
10     Sunny        Mild   Normal  Strong  Yes
11  Overcast        Mild     High  Strong  Yes
12  Overcast         Hot   Normal    Weak  Yes
13      Rain        Mild     High  Strong   No

In [4]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

### Encoding strings to numbers

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le = LabelEncoder()

In [7]:
X = np.apply_along_axis(le.fit_transform, 0, X)
y = le.fit_transform(y)

In [8]:
X

array([[2, 1, 0, 1],
       [2, 1, 0, 0],
       [0, 1, 0, 1],
       [1, 2, 0, 1],
       [1, 0, 1, 1],
       [1, 0, 1, 0],
       [0, 0, 1, 0],
       [2, 2, 0, 1],
       [2, 0, 1, 1],
       [1, 2, 1, 1],
       [2, 2, 1, 0],
       [0, 2, 0, 0],
       [0, 1, 1, 1],
       [1, 2, 0, 0]])

### Training the model

In [9]:
from sklearn.naive_bayes import GaussianNB

In [10]:
classifier = GaussianNB()
classifier.fit(X, y)

GaussianNB()

### Predicting the result

In [11]:
classifier.predict([le.fit_transform(['overcast', 'cool', 'normal', 'weak']),
                    le.fit_transform(['rain', 'mild', 'normal', 'strong']),
                    le.fit_transform(['sunny', 'hot', 'high', 'weak'])])

array([1, 1, 0])

In [12]:
y_pred = classifier.predict(X)

### Confusion matrix

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [14]:
confusion_matrix(y, y_pred)

array([[4, 1],
       [0, 9]], dtype=int64)

In [15]:
accuracy_score(y, y_pred)

0.9285714285714286

In [16]:
classifier.score(X, y)

0.9285714285714286